# Generated by Django 4.2.5 on 2023-09-19 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_product_date_added'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Item',
        ),
    ]
